config/routes.rb
Rails.application.routes.draw do
  root to: 'domains#index'

  resources :sessions, only: [:create]

  get :login, to: 'sessions#new', as: :login
  get :logout, to: 'sessions#destroy', as: :logout

  resources :domains, shallow: true do
    resources :users, except: [:index, :show]
    resources :aliases, except: [:index]
    resources :recipient_bccs, except: [:index, :show]
    resources :sender_bccs, except: [:index, :show]
  end

  resources :api_clients, except: [:show]
  resources :client_accesses, except: [:show]
  resources :recipient_accesses, except: [:show]
  resources :sender_accesses, except: [:show]
  resources :workgroups, except: [:show]

  namespace :api, defaults: { format: :json } do
    resources :domains, only: [:index, :show] do
      member do
        get :users
        get :aliases
        get :recipient_bccs
        get :sender_bccs
      end
    end

    resources :users, only: [:show, :create, :update, :destroy]
    resources :aliases, only: [:show, :create, :update, :destroy]
    resources :recipient_bccs, only: [:show, :create, :update, :destroy]
    resources :sender_bccs, only: [:show, :create, :update, :destroy]
  end
end

app/views/shared/_error_messages.js.erb
<% if object.valid? %>
  location.href = '<%=target_path%>';
<% else %>
  <% (object.attribute_names + object.errors.keys.map(&:to_s)).uniq.each do |field| %>
    <% if object.errors[field].any? %>
      $('#<%=object.class.to_s.underscore%>_<%=field%>')
        .parents('.form-group')
        .addClass('has-error')
        .find('.help-block')
        .html('<%= j object.errors[field].first %>');
    <% else %>
      $('#<%=object.class.to_s.underscore%>_<%=field%>')
        .parents('.form-group')
        .removeClass('has-error');

      $('#<%=object.class.to_s.underscore%>_<%=field%>')
        .parents('.form-group')
        .find('.help-block')
        .html('');
    <% end %>
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-collapse collapse" id="navbar-main">
  <ul class="nav navbar-nav">
    <li class="dropdown menu-list" data-menu="menu">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="themes">Administracion <span class="caret"></span></a>
      <ul class="dropdown-menu" aria-labelledby="themes">
        <li>
          <%= link_to 'Dominios', domains_path, tabindex: -1 %>

          <% if current_user.has_role?(:administrator) %>
            <%= link_to 'Grupos de trabajo', workgroups_path, tabindex: -1 %>
            <%= link_to 'Clientes api', api_clients_path, tabindex: -1 %>
            <%= link_to 'Restricción de clientes', client_accesses_path, tabindex: -1 %>
            <%= link_to 'Restricción de emisores', sender_accesses_path, tabindex: -1 %>
            <%= link_to 'Restricción de receptores', recipient_accesses_path, tabindex: -1 %>
          <% end %>
        </li>
      </ul>
    </li>
  </ul>
  <ul class="nav navbar-nav navbar-right">
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <span class="glyphicon glyphicon-user"></span>
      <%=current_user.email%> <b class="caret"></b>
      </a>
      <ul class="dropdown-menu">
        <li><%= link_to 'Salir', logout_url, tabindex: -1 %></li>
      </ul>
    </li>
  </ul>
</div>