config/routes.rb
Rails.application.routes.draw do
  root to: 'domains#index'

  resources :sessions, only: [:create]

  get :login, to: 'sessions#new', as: :login
  get :logout, to: 'sessions#destroy', as: :logout

  resources :domains, shallow: true do
    resources :users, except: [:index, :show]
    resources :aliases, except: [:index]
    resources :recipient_bccs, except: [:index, :show]
    resources :sender_bccs, except: [:index, :show]
  end

  resources :api_clients, except: [:show]
  resources :client_accesses, except: [:show]
  resources :recipient_accesses, except: [:show]
  resources :sender_accesses, except: [:show]
  resources :workgroups, except: [:show]

  namespace :api, defaults: { format: :json } do
    resources :domains, only: [:index, :show] do
      member do
        get :users
        get :aliases
        get :recipient_bccs
        get :sender_bccs
      end
    end

    resources :users, only: [:show, :create, :update, :destroy]
    resources :aliases, only: [:show, :create, :update, :destroy]
    resources :recipient_bccs, only: [:show, :create, :update, :destroy]
    resources :sender_bccs, only: [:show, :create, :update, :destroy]
  end
end

app/controllers/recipient_accesses_controller.rb
class RecipientAccessesController < ApplicationController
  before_action :check_if_administrator

  def index
    @recipient_accesses = RecipientAccess.all
  end

  def show
    @recipient_access = RecipientAccess.find(params[:id])
  end

  def new
    @recipient_access = RecipientAccess.new({
      enabled: true,
      status: 'reject'
    })

    @statuses = [[I18n.t('access_status.reject'), 'reject'], [I18n.t('access_status.ok'), 'ok']]
  end

  def create
    @recipient_access = RecipientAccess.new(permitted_params)
    @recipient_access.save

    respond_to do |format|
      format.js do
        render partial: 'shared/error_messages', locals: {
          object: @recipient_access, target_path: recipient_accesses_path
        }
      end
    end
  end

  def edit
    @recipient_access = RecipientAccess.find(params[:id])

    @statuses = [[I18n.t('access_status.reject'), 'reject'], [I18n.t('access_status.ok'), 'ok']]
  end

  def update
    @recipient_access = RecipientAccess.find(params[:id])
    @recipient_access.update_attributes(permitted_params)

    respond_to do |format|
      format.js do
        render partial: 'shared/error_messages', locals: {
          object: @recipient_access, target_path: recipient_accesses_path
        }
      end
    end
  end

  def destroy
    @recipient_access = RecipientAccess.find(params[:id])
    @recipient_access.destroy

    redirect_to recipient_accesses_path
  end

  protected

  def permitted_params
    params[:recipient_access].permit(:name, :status, :reject_note, :observations, :enabled)
  end
end

app/views/recipient_accesses/_form.html.erb
<div class="row">
  <div class="col-md-5">
    <%= form_for @recipient_access, remote: true, html: {role: :form} do |f| %>
      <div class="form-group">
        <%= f.label :name, class: 'control-label' %>
        <%= f.text_field :name, class: 'form-control', autofocus: true %>
        <span class="help-block"></span>
      </div>

      <div class="form-group">
        <%= f.label :status, class: 'control-label' %>
        <%= f.select :status, @statuses, { }, class: 'form-control' %>
        <span class="help-block"></span>
      </div>

      <div class="form-group">
        <%= f.label :reject_note, class: 'control-label' %>
        <%= f.text_field :reject_note, class: 'form-control' %>
        <span class="help-block"></span>
      </div>

      <div class="form-group">
        <%= f.label :observations, class: 'control-label' %>
        <%= f.text_area :observations, class: 'form-control' %>
        <span class="help-block"></span>
      </div>

      <div class="checkbox">
        <label>
          <%= f.check_box :enabled %>
          <%= RecipientAccess.human_attribute_name :enabled %>
        </label>
      </div>

      <%= link_to_cancel recipient_accesses_path %>
      <%= f.submit class: 'btn btn-primary' %>

      <% unless @recipient_access.new_record? %>
        <%= link_to_delete recipient_access_path(@recipient_access) %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/recipient_accesses/edit.html.erb
<div class="breadcrumb-container">
  <ul class="breadcrumb">
    <li><%= link_to RecipientAccess.model_name.human(count: 2), client_accesses_path %></li>
    <li class="active"><%=t('.title')%></li>
  </ul>
</div>

<h3><%=t('.title')%></h3>

<%= render 'form' %>

app/views/recipient_accesses/index.html.erb
<h3><%=t('.title')%></h3>

<table class="table table-bordered">
  <thead>
    <tr>
      <th><%= RecipientAccess.human_attribute_name :id %></th>
      <th><%= RecipientAccess.human_attribute_name :name %></th>
      <th><%= RecipientAccess.human_attribute_name :status %></th>
      <th><%= RecipientAccess.human_attribute_name :reject_note %></th>
      <th><%= RecipientAccess.human_attribute_name :enabled %></th>
    </tr>
  </thead>

  <tbody>
    <% if @recipient_accesses.empty? %>
      <tr>
        <td colspan="100%" class="text-center"><%=t('tables.no_records')%></td>
      </tr>
    <% end %>
    <% @recipient_accesses.each do |recipient_access| %>
      <tr>
        <td><%= link_to recipient_access.id, edit_recipient_access_path(recipient_access) %></td>
        <td><%= recipient_access.name %></td>
        <td><%= I18n.t("access_status.#{recipient_access.status}") %></td>
        <td><%= recipient_access.reject_note %></td>
        <td><%= bool_t(recipient_access.enabled) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to_new new_recipient_access_path %>

app/views/recipient_accesses/new.html.erb
<div class="breadcrumb-container">
  <ul class="breadcrumb">
    <li><%= link_to RecipientAccess.model_name.human(count: 2), client_accesses_path %></li>
    <li class="active"><%=t('.title')%></li>
  </ul>
</div>

<h3><%=t('.title')%></h3>

<%= render 'form' %>