config/routes.rb
Rails.application.routes.draw do
  root to: 'domains#index'

  resources :sessions, only: [:create]

  get :login, to: 'sessions#new', as: :login
  get :logout, to: 'sessions#destroy', as: :logout

  resources :domains, shallow: true do
    resources :users, except: [:index, :show]
    resources :aliases, except: [:index]
    resources :recipient_bccs, except: [:index, :show]
    resources :sender_bccs, except: [:index, :show]
  end

  resources :api_clients, except: [:show]
  resources :client_accesses, except: [:show]
  resources :recipient_accesses, except: [:show]
  resources :sender_accesses, except: [:show]
  resources :workgroups, except: [:show]

  namespace :api, defaults: { format: :json } do
    resources :domains, only: [:index, :show] do
      member do
        get :users
        get :aliases
        get :recipient_bccs
        get :sender_bccs
      end
    end

    resources :users, only: [:show, :create, :update, :destroy]
    resources :aliases, only: [:show, :create, :update, :destroy]
    resources :recipient_bccs, only: [:show, :create, :update, :destroy]
    resources :sender_bccs, only: [:show, :create, :update, :destroy]
  end
end

app/models/domain.rb
class Domain < ApplicationRecord
  validates :name, presence: true, uniqueness: { case_sensitive: false }, domain: true

  belongs_to :workgroup
  has_many :aliases, dependent: :destroy
  has_many :users, dependent: :destroy
  has_many :recipient_bccs, dependent: :destroy
  has_many :sender_bccs, dependent: :destroy

  scope :enabled, -> { where({ enabled: true }) }

  default_scope -> { order(:name) }

  def has_data?
    aliases.any? || users.any? || recipient_bccs.any? || sender_bccs.any?
  end
end

app/controllers/api/domains_controller.rb
class Api::DomainsController < Api::BaseApiController
  def index
    result = Domain.all

    if params[:show_disabled] != 'true'
      result.where!({ enabled: true })
    end

    if params[:name].present?
      result.where!(name: params[:name])
    end

    render json: result
  end

  def show
    render json: Domain.find(params[:id])
  end

  def users
    result = User.where(domain_id: params[:id])

    if params[:enabled].present?
      result.where!(enabled: ['1', 'true'].include?(params[:enabled]))
    end

    if params[:email].present?
      result.where!(email: params[:email])
    end

    render json: result
  end

  def aliases
    result = Alias.where(domain_id: params[:id])

    if params[:show_disabled] != 'true'
      result.where!({ enabled: true })
    end

    if params[:name].present?
      result.where!(name: params[:name])
    end

    if params[:from].present?
      result.where!(from: params[:from])
    end

    if params[:to].present?
      result.where!("aliases.to LIKE ?", "%#{params[:to]}%")
    end

    render json: result
  end

  def recipient_bccs
    result = RecipientBcc.where(domain_id: params[:id])

    if params[:show_disabled] != 'true'
      result.where!({ enabled: true })
    end

    if params[:from].present?
      result.where!(from: params[:from])
    end

    if params[:to].present?
      result.where!("recipient_bccs.to LIKE ?", "%#{params[:to]}%")
    end

    render json: result
  end

  def sender_bccs
    result = SenderBcc.where(domain_id: params[:id])

    if params[:show_disabled] != 'true'
      result.where!({ enabled: true })
    end

    if params[:from].present?
      result.where!(from: params[:from])
    end

    if params[:to].present?
      result.where!("sender_bccs.to LIKE ?", "%#{params[:to]}%")
    end

    render json: result
  end
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  before_action :check_if_administrator, except: [:index, :show]

  def index
    @domains = Domain.all

    unless current_user.has_role?(:administrator)
      if current_user.domain.workgroup_id.present?
        @domains.where!({workgroup_id: current_user.domain.workgroup_id })
      else
        @domains = []
      end
    end
  end

  def show
    @domain = Domain.find(params[:id])

    @workgroups = Workgroup.all
  end

  def new
    @domain = Domain.new(enabled: true)

    @workgroups = Workgroup.all
  end

  def create
    @domain = Domain.new(permitted_params)
    @domain.save

    respond_to do |format|
      format.js do
        render partial: 'shared/error_messages', locals: {
          object: @domain, target_path: domains_path
        }
      end
    end
  end

  def update
    @domain = Domain.find(params[:id])
    @domain.update_attributes(permitted_params)

    respond_to do |format|
      format.js do
        render partial: 'shared/error_messages', locals: {
          object: @domain, target_path: domains_path
        }
      end
    end
  end

  def destroy
    @domain = Domain.find(params[:id])

    unless @domain.has_data?
      @domain.destroy
    end

    redirect_to domains_path
  end

  protected

  def permitted_params
    params[:domain].permit(:name, :enabled, :workgroup_id)
  end
end

app/views/domains/_form.html.erb
<div class="row">
  <div class="col-md-4">
    <%= form_for @domain, remote: true, html: {role: :form} do |f| %>
      <% if @domain.new_record? %>
        <div class="form-group">
          <%= f.label :name, class: 'control-label' %>
          <%= f.text_field :name, class: 'form-control', autofocus: true %>
          <span class="help-block"></span>
        </div>
      <% end %>

      <div class="checkbox">
        <label>
          <%= f.check_box :enabled %>
          <%= Domain.human_attribute_name :enabled %>
        </label>
      </div>

      <% if current_user.has_role?(:administrator) %>
        <div class="form-group">
          <%= f.label :workgroup_id, class: 'control-label' %>
          <%= f.select :workgroup_id, @workgroups.map { |x| [x.name, x.id] }, { include_blank: true }, class: 'form-control' %>
          <span class="help-block"></span>
        </div>
      <% end %>

      <% if @domain.new_record? %>
        <%= link_to_cancel root_path %>
        <%= f.submit class: 'btn btn-primary' %>
      <% else %>
        <%= f.submit class: 'btn btn-primary', data: { confirm: I18n.t('confirm.update_domain') } %>
      <% end %>

      <% unless @domain.new_record? || @domain.has_data? %>
        <%= link_to_delete domain_path(@domain) %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/domains/_show_aliases.html.erb
<div class="tab-pane fade" id="aliases">
  <div class="actions-pane">
    <%= link_to_new new_domain_alias_path(@domain) %>
  </div>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th><%= Alias.human_attribute_name :id %></th>
        <th><%= Alias.human_attribute_name :name %></th>
        <th><%= Alias.human_attribute_name :from %></th>
        <th><%= Alias.human_attribute_name :to %></th>
        <th><%= Alias.human_attribute_name :enabled %></th>
        <th><%= Alias.human_attribute_name :created_at %></th>
      </tr>
    </thead>

    <tbody>
      <% if @domain.aliases.empty? %>
        <tr>
          <td colspan="100%" class="text-center"><%=t('tables.no_records')%></td>
        </tr>
      <% end %>
      <% @domain.aliases.each do |ali| %>
        <tr>
          <td><%= link_to ali.id, edit_alias_path(ali) %></td>
          <td><%= ali.name %></td>
          <td><%= ali.from %></td>
          <td>
            <% if ali.recipients.count > 2 %>
              <%= link_to "#{ali.recipients.first(2).join(', ')}, ...", alias_path(ali), class: 'fancybox' %>
            <% else %>
              <%= ali.recipients.join(', ') %>
            <% end %>
          </td>
          <td><%= bool_t(ali.enabled) %></td>
          <td><%= l ali.created_at %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/domains/_show_recipient_bccs.html.erb
<div class="tab-pane fade" id="recipient_bccs">
  <div class="actions-pane">
    <%= link_to_new new_domain_recipient_bcc_path(@domain) %>
  </div>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th><%= RecipientBcc.human_attribute_name :id %></th>
        <th><%= RecipientBcc.human_attribute_name :from %></th>
        <th><%= RecipientBcc.human_attribute_name :to %></th>
        <th><%= RecipientBcc.human_attribute_name :enabled %></th>
        <th><%= RecipientBcc.human_attribute_name :created_at %></th>
      </tr>
    </thead>

    <tbody>
      <% if @domain.recipient_bccs.empty? %>
        <tr>
          <td colspan="100%" class="text-center"><%=t('tables.no_records')%></td>
        </tr>
      <% end %>
      <% @domain.recipient_bccs.each do |bcc| %>
        <tr>
          <td><%= link_to bcc.id, edit_recipient_bcc_path(bcc) %></td>
          <td><%= bcc.from %></td>
          <td><%= bcc.to %></td>
          <td><%= bool_t(bcc.enabled) %></td>
          <td><%= l bcc.created_at %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/domains/_show_sender_bccs.html.erb
<div class="tab-pane fade" id="sender_bccs">
  <div class="actions-pane">
    <%= link_to_new new_domain_sender_bcc_path(@domain) %>
  </div>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th><%= SenderBcc.human_attribute_name :id %></th>
        <th><%= SenderBcc.human_attribute_name :from %></th>
        <th><%= SenderBcc.human_attribute_name :to %></th>
        <th><%= SenderBcc.human_attribute_name :enabled %></th>
        <th><%= SenderBcc.human_attribute_name :created_at %></th>
      </tr>
    </thead>

    <tbody>
      <% if @domain.sender_bccs.empty? %>
        <tr>
          <td colspan="100%" class="text-center"><%=t('tables.no_records')%></td>
        </tr>
      <% end %>
      <% @domain.sender_bccs.each do |bcc| %>
        <tr>
          <td><%= link_to bcc.id, edit_sender_bcc_path(bcc) %></td>
          <td><%= bcc.from %></td>
          <td><%= bcc.to %></td>
          <td><%= bool_t(bcc.enabled) %></td>
          <td><%= l bcc.created_at %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/domains/_show_users.html.erb
<div class="tab-pane fade active in" id="users">
  <div class="actions-pane">
    <%= link_to_new new_domain_user_path(@domain) %>
  </div>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th><%= User.human_attribute_name :id %></th>
        <th><%= User.human_attribute_name :name %></th>
        <th><%= User.human_attribute_name :email %></th>
        <th><%= User.human_attribute_name :role_code %></th>
        <th><%= User.human_attribute_name :enabled %></th>
        <th><%= User.human_attribute_name :created_at %></th>
      </tr>
    </thead>

    <tbody>
      <% if @domain.users.empty? %>
        <tr>
          <td colspan="100%" class="text-center"><%=t('tables.no_records')%></td>
        </tr>
      <% end %>
      <% @domain.users.each do |user| %>
        <tr>
          <td><%= link_to user.id, edit_user_path(user) %></td>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= user.role.try(:name) %></td>
          <td><%= bool_t(user.enabled) %></td>
          <td><%= l user.created_at %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/domains/index.html.erb
<h3><%=t('.title')%></h3>

<table class="table table-bordered">
  <thead>
    <tr>
      <th><%= Domain.human_attribute_name :id %></th>
      <th><%= Domain.human_attribute_name :name %></th>
      <th><%= Domain.human_attribute_name :workgroup_id %></th>
      <th><%= Domain.human_attribute_name :enabled %></th>
      <th><%= Domain.human_attribute_name :created_at %></th>
    </tr>
  </thead>

  <tbody>
    <% if @domains.empty? %>
      <tr>
        <td colspan="100%" class="text-center"><%=t('tables.no_records')%></td>
      </tr>
    <% end %>
    <% @domains.each do |domain| %>
      <tr>
        <td><%= link_to domain.id, domain_path(domain) %></td>
        <td><%= domain.name %></td>
        <td><%= domain.workgroup.try(:name) %></td>
        <td><%= bool_t(domain.enabled) %></td>
        <td><%= l domain.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to_new new_domain_path %>

app/views/domains/new.html.erb
<div class="breadcrumb-container">
  <ul class="breadcrumb">
    <li><%= link_to Domain.model_name.human(count: 2), root_path %></li>
    <li class="active"><%=t('.title')%></li>
  </ul>
</div>

<h3><%=t('.title')%></h3>

<%= render 'form' %>

app/views/domains/show.html.erb
<div class="breadcrumb-container">
  <ul class="breadcrumb">
    <li><%= link_to Domain.model_name.human(count: 2), root_path %></li>
    <li class="active"><%=@domain.name%></li>
  </ul>
</div>

<% if current_user.has_role?(:administrator) %>
  <%= render 'form' %>
<% end %>

<hr />

<div class="nav-container">
  <ul class="nav nav-tabs">
    <li class="active users-tab">
      <a href="#users" data-toggle="tab"><%=User.model_name.human(count: 2)%></a>
    </li>
    <li class="aliases-tab">
      <a href="#aliases" data-toggle="tab"><%=Alias.model_name.human(count: 2)%></a>
    </li>
    <li class="sender_bccs-tab">
      <a href="#sender_bccs" data-toggle="tab"><%=SenderBcc.model_name.human(count: 2)%></a>
    </li>
    <li class="recipient_bccs-tab">
      <a href="#recipient_bccs" data-toggle="tab"><%=RecipientBcc.model_name.human(count: 2)%></a>
    </li>
  </ul>
</div>

<div class="tab-content">
  <%= render 'show_users' %>
  <%= render 'show_aliases' %>
  <%= render 'show_sender_bccs' %>
  <%= render 'show_recipient_bccs' %>
</div>